import { useState } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { API } from '../api/client'
import { useToast } from '../components/Toast'
import { homeForRole } from '../utils/helpers'

export function Login(){
 const {user,login}=useAuth(); const nav=useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 if(user) return <Navigate to={homeForRole(user.role)} replace/>
 async function submit(){setError('');if(!email||!password){setError('Please fill in both fields.');return}setBusy(true);try{const u=await login(email.trim(),password);nav(homeForRole(u.role),{replace:true})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="auth-screen"><div className="auth-left"><div className="auth-brand"><div className="auth-brand-mark">S</div><span className="auth-brand-name">SAFARA</span></div><h1 className="auth-headline">Stay aware.<br/>Travel safer.</h1><p className="auth-tagline">SAFARA is a navigation and safety console for Mangaluru. Sign in with your account. Roles come from the server, not this screen.</p><div className="auth-pills"><span className="auth-pill">Community reports</span><span className="auth-pill">Lower reported-incident exposure</span><span className="auth-pill">District command</span></div></div><div className="auth-right"><div className="auth-form-wrap"><h2 className="auth-form-title">Welcome back</h2><p className="auth-form-sub">Sign in to open the user app, officer console, or admin console.</p>{error&&<div className="auth-error">{error}</div>}<div className="field"><label>Email Address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com"/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" onKeyDown={e=>e.key==='Enter'&&submit()}/></div><button className="btn-primary" onClick={submit} disabled={busy} style={{marginBottom:16}}>{busy?'Signing in…':'Sign in'}</button><div className="auth-switch">New here? <Link to="/signup">Create an account</Link></div><div className="auth-demo-hint">NGO applications are available after you sign in as a resident.</div></div></div></div>
}

export function Signup(){
 const {user,register}=useAuth();const nav=useNavigate();const [f,setF]=useState({name:'',city:'',email:'',password:'',confirm:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);if(user)return <Navigate to={homeForRole(user.role)} replace/>;const set=(k,v)=>setF(x=>({...x,[k]:v}));
 async function submit(){setError('');if(!f.name.trim())return setError('Name is required.');if(!/\S+@\S+\.\S+/.test(f.email))return setError('Valid email required.');if(f.password.length<8)return setError('Minimum 8 characters.');if(f.password!==f.confirm)return setError('Passwords do not match.');setBusy(true);try{const u=await register({name:f.name.trim(),email:f.email.trim(),password:f.password});nav(homeForRole(u.role),{replace:true})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <AuthCard title="Create Account" subtitle="Join SAFARA to report incidents and use navigation in a later phase."><div>{error&&<div className="auth-error">{error}</div>}<div className="field-row"><div className="field"><label>Full Name</label><input value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Priya Sharma"/></div><div className="field"><label>City</label><input value={f.city} onChange={e=>set('city',e.target.value)} placeholder="Mangaluru"/></div></div><div className="field"><label>Email Address</label><input type="email" value={f.email} onChange={e=>set('email',e.target.value)} placeholder="you@email.com"/></div><div className="field-row"><div className="field"><label>Password</label><input type="password" value={f.password} onChange={e=>set('password',e.target.value)} placeholder="••••••••"/></div><div className="field"><label>Confirm</label><input type="password" value={f.confirm} onChange={e=>set('confirm',e.target.value)} placeholder="••••••••"/></div></div><button className="btn-primary" onClick={submit} disabled={busy}>{busy?'Creating account…':'Create Account →'}</button><div style={{textAlign:'center',marginTop:16,fontSize:'.84rem',color:'var(--muted)'}}>Already have an account? <Link to="/login" style={{color:'var(--blue)',fontWeight:600}}>Sign in</Link></div></div></AuthCard>
}
function AuthCard({title,subtitle,children}){return <div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',background:'var(--bg)',padding:'24px 16px'}}><div style={{background:'var(--card)',borderRadius:20,padding:'40px 36px',width:'100%',maxWidth:440,border:'1px solid var(--border)'}}><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:28}}><div className="brand-mark">S</div><span className="brand-name">SAFARA</span></div><h2 className="page-title" style={{fontSize:'1.8rem',marginBottom:8}}>{title}</h2><p className="page-sub" style={{marginBottom:28}}>{subtitle}</p>{children}</div></div>}

export function NgoRegister(){
 const {user}=useAuth();const [org,setOrg]=useState('');const [reg,setReg]=useState('');const [desc,setDesc]=useState('');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const toast=useToast();
 if(!user)return <Navigate to="/login" replace/>
 async function submit(){if(!org.trim()){toast.show('Organisation required','Enter the organisation name.','⚠️');return}setBusy(true);try{await API.ngoApply({organization_name:org.trim(),registration_number:reg.trim()||undefined,description:desc.trim()||undefined});setDone(true);toast.show('Submitted for review','Admin approval is required.','🛡')}catch(e){toast.show('Registration failed',e.message,'⚠️')}finally{setBusy(false)}}
 return <AuthCard title="NGO / Officer Registration" subtitle="Submit your organization for admin review. Your existing SAFARA user account will be promoted to NGO_OFFICER only after approval."><div className="ngo-notice"><span>⏳</span><span>Current account: <strong>{user.email}</strong>. No second password or separate account is created.</span></div>{done?<div className="submitted-box"><div style={{fontSize:'3rem',marginBottom:16}}>✅</div><h2 className="page-title" style={{fontSize:'1.6rem',marginBottom:12}}>Application Submitted</h2><p style={{fontSize:'.86rem',color:'var(--muted)',lineHeight:1.7,marginBottom:28}}>Your application is pending admin approval. Until approval, your role remains USER.</p><Link className="btn-primary" to="/app">Back to SAFARA</Link></div>:<><div className="field"><label>Organization Name</label><input value={org} onChange={e=>setOrg(e.target.value)} placeholder="Safe City Foundation"/></div><div className="field"><label>Registration Number</label><input value={reg} onChange={e=>setReg(e.target.value)} placeholder="NGO-KA-2024-001"/></div><div className="field"><label>Description</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Tell the SAFARA admin team about your organization." style={{minHeight:110,resize:'vertical'}}/></div><button className="btn-primary" onClick={submit} disabled={busy}>{busy?'Submitting…':'Submit for Review →'}</button></>}</AuthCard>
}
