import { useEffect, useState } from 'react'
import { AppShell } from '../components/Shell'
import { API } from '../api/client'
import { useToast } from '../components/Toast'
import { getAccuratePosition } from '../utils/geo'

function icon(type=''){const x=type.toLowerCase();if(x.includes('police'))return'👮';if(x.includes('ambulance')||x.includes('medical'))return'🚑';if(x.includes('fire'))return'🔥';if(x.includes('cyber'))return'💻';if(x.includes('ngo')||x.includes('support'))return'🤝';return'📞'}
export default function Emergency(){const [contacts,setContacts]=useState([]);const [sos,setSos]=useState([]);const toast=useToast();useEffect(()=>{Promise.all([API.contacts(),API.sos()]).then(([c,s])=>{setContacts(c);setSos(s)}).catch(e=>toast.show('Emergency data unavailable',e.message,'⚠️'))},[]);async function send(){if(!navigator.geolocation)return toast.show('Location unavailable','Enable GPS to send SOS.','⚠️');getAccuratePosition().then(async p=>{try{await API.createSOS({latitude:p.coords.latitude,longitude:p.coords.longitude,message:'SOS alert from SAFARA'});toast.show('SOS sent','Your emergency alert is active.','🚨');setSos(await API.sos())}catch(e){toast.show('SOS failed',e.message,'⚠️')}}).catch(()=>toast.show('Location unavailable','Allow location access to send SOS.','⚠️'))}
return <AppShell active="ngo"><div className="content-panel"><h2 className="panel-title">Emergency & SOS</h2><p className="panel-sub">Quickly contact emergency services or send your current location to SAFARA officers.</p><div className="card" style={{textAlign:'center',padding:28}}><div style={{fontSize:'2.4rem'}}>🚨</div><h3 style={{color:'var(--navy)',margin:'8px 0'}}>Need immediate help?</h3><p style={{color:'var(--muted)',fontSize:'.84rem',marginBottom:18}}>Allow location access and SAFARA will create an active SOS record.</p><button className="sos-send-btn" onClick={send}>SEND SOS ALERT</button></div><div className="contact-grid">{contacts.length?contacts.map(c=><div className="contact-card" key={c.id}><div className="contact-icon-row"><div className="contact-icon">{icon(c.type)}</div><div><div className="contact-name">{c.name}</div><div className="contact-num">📞 {c.phone}</div></div></div><p className="contact-desc">{[c.organization,c.type,c.city].filter(Boolean).join(' · ')||'Emergency contact'}</p><div className="contact-btns"><button className="btn-call" onClick={()=>window.location.href=`tel:${c.phone}`}>📞 Call</button><button className="btn-alert" onClick={()=>toast.show(`Alert sent to ${c.name}`,'Emergency contact notified.','🔔')}>🔔 Alert</button></div></div>):<div className="contact-card">No emergency contacts are available.</div>}</div>{sos.length>0&&<div className="card"><div className="card-header"><span className="card-title">Your SOS alerts</span></div>{sos.slice(0,5).map(x=><div className="incident-row" key={x.id}><strong>#{x.id}</strong> · {x.status} · {x.created_at}</div>)}</div>}</div></AppShell>}
