import { useState } from 'react'
import { AppShell } from '../components/Shell'
import { API } from '../api/client'
import { useToast } from '../components/Toast'

export default function Report(){const toast=useToast();const [type,setType]=useState('');const [location,setLocation]=useState('');const [desc,setDesc]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState(null);const types=[['Harassment','⚠️'],['Suspicious Activity','👁'],['Theft / Snatching','💼'],['Unsafe Environment','🌑']]
 async function geocode(q){const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(q)}&limit=1`,{headers:{'Accept-Language':'en'}});const d=await r.json();return d?.[0]?[parseFloat(d[0].lat),parseFloat(d[0].lon)]:null}
 async function submit(){if(!location.trim()){toast.show('Location required','Please enter a location.','⚠️');return}if(!desc.trim()){toast.show('Description required','Describe what happened.','⚠️');return}setBusy(true);try{const description=`${type?`${type}: `:''}${desc.trim()}`;const [ai,coords]=await Promise.all([API.classifyIncident(description),geocode(location)]);if(!coords)throw new Error('We could not locate this address. Add a nearby landmark or city.');const r=await API.createIncident({description,latitude:coords[0],longitude:coords[1],address:location.trim()});setResult({incident:r.incident,ai});toast.show('Report submitted','Your incident was saved to SAFARA.','✅')}catch(e){toast.show('Report not submitted',e.message,'⚠️')}finally{setBusy(false)}}
 function reset(){setResult(null);setType('');setLocation('');setDesc('')}
 return <AppShell active="report"><div className="content-panel"><div><h2 className="panel-title">Report Incident</h2><p className="panel-sub">Your report enters the SAFARA AI classification pipeline before affecting safety data.</p></div>{!result?<><div className="card"><div className="card-header"><span className="card-title">Incident Type</span></div><div className="incident-type-grid">{types.map(([t,icon])=><button key={t} className={`type-option${type===t?' selected':''}`} onClick={()=>setType(t)}>{icon} {t}</button>)}</div><div className="field"><label>Location</label><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. MG Road Bus Stop, Mangaluru"/></div><div className="field"><label>Description <span style={{fontWeight:400,textTransform:'none',letterSpacing:0,color:'var(--muted)'}}>(AI will analyse this)</span></label><textarea value={desc} onChange={e=>setDesc(e.target.value)} style={{minHeight:90,resize:'vertical'}} placeholder="Describe what happened. SAFARA will classify category and severity."/></div><button className="submit-btn" onClick={submit} disabled={busy}>{busy?'Analysing & Submitting…':'Submit Report'}</button></div><div className="card" style={{background:'#eff6ff',border:'1px solid #bfdbfe'}}><div className="card-header"><span className="card-title" style={{color:'var(--blue)'}}>🤖 How AI Classification Works</span></div><p style={{fontSize:'.82rem',color:'var(--muted)',lineHeight:1.75}}>The Flask backend sends the incident description through SAFARA's configured server-side AI classifier. The client never receives or stores the Gemini API key.</p></div></>:<><div className="card" id="ai-result-card"><div className="card-header"><span className="card-title">🤖 AI Analysis Result</span><span className="card-badge badge-blue">{result.incident?.severity||result.ai?.severity}</span></div><p style={{fontSize:'.85rem',color:'var(--text)',lineHeight:1.7}}>Category: <strong>{result.incident?.category||result.ai?.category}</strong></p><p style={{fontSize:'.83rem',color:'var(--muted)',lineHeight:1.6}}>Confidence: {result.incident?.ai_confidence!=null?Number(result.incident.ai_confidence).toFixed(2):result.ai?.confidence??'—'} · Source: {result.incident?.classification_source||result.ai?.source||'AI'}</p><p style={{fontSize:'.83rem',color:'var(--muted)',lineHeight:1.6,fontStyle:'italic'}}>Report ID: #{result.incident?.id}</p></div><div className="success-msg"><div className="success-icon">✅</div><div className="success-title">Thank you for your report.</div><div className="success-body">SAFARA has stored the report and its server-side classification. Verified incidents can contribute to safer routing.</div></div><button className="submit-btn" style={{maxWidth:220}} onClick={reset}>Submit another</button></>}</div></AppShell>}
